# Generated by Django 3.1.5 on 2021-01-26 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0059_apply_collection_ordering"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook", models.URLField(blank=True, help_text="Facebook URL")),
                ("twitter", models.URLField(blank=True, help_text="Twitter URL")),
                ("instagram", models.URLField(blank=True, help_text="Instagram URL")),
                (
                    "youtube",
                    models.URLField(blank=True, help_text="YouTube Channel URL"),
                ),
                ("linkedin", models.URLField(blank=True, help_text="LinkedIn URL")),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={"verbose_name": "Social Media",},
        ),
        migrations.CreateModel(
            name="LegalSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("copyright", models.TextField(blank=True)),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={"verbose_name": "Legal",},
        ),
    ]
