# Generated by Django 3.1.5 on 2021-07-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='github',
            field=models.URLField(blank=True, help_text='Github URL'),
        ),
    ]
