# Installed Apps
# https://docs.djangoproject.com/en/3.1/ref/settings/#installed-apps

INSTALLED_APPS = [
    "corsheaders",
    "django_extensions",
    "modelcluster",
    "taggit",
    "wagtailmenus",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.modeladmin",
    "wagtail.contrib.settings",
    "wagtail.contrib.styleguide",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail.core",
    "wagtail_modeltranslation",
    "wagtail_modeltranslation.makemigrations",
    "wagtail_modeltranslation.migrate",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.sessions",
    "django.contrib.staticfiles",
    "common.apps.CommonConfig",
    "configuration.apps.ConfigurationConfig",
    "pages.about.apps.AboutConfig",
    "pages.example.apps.ExampleConfig",
    "pages.home.apps.HomeConfig",
    "pages.flex.apps.FlexConfig",
]
