# Generated by Django 3.1.5 on 2021-01-26 21:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0059_apply_collection_ordering"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamplePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("body", wagtail.core.fields.RichTextField(blank=True)),
                ("body_en", wagtail.core.fields.RichTextField(blank=True, null=True)),
                ("body_fr", wagtail.core.fields.RichTextField(blank=True, null=True)),
            ],
            options={"verbose_name": "Example Page",},
            bases=("wagtailcore.page",),
        ),
    ]
