# Generated by Django 3.1.5 on 2021-07-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body_fr',
        ),
    ]
