# Generated by Django 3.1.5 on 2021-01-25 21:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0059_apply_collection_ordering"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.core.blocks.CharBlock(
                                    form_classname="full title"
                                ),
                            ),
                            ("paragraph", wagtail.core.blocks.RichTextBlock()),
                            (
                                "team",
                                wagtail.core.blocks.ListBlock(
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "first_name",
                                                wagtail.core.blocks.CharBlock(),
                                            ),
                                            (
                                                "last_name",
                                                wagtail.core.blocks.CharBlock(),
                                            ),
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "bio",
                                                wagtail.core.blocks.RichTextBlock(),
                                            ),
                                        ]
                                    )
                                ),
                            ),
                        ]
                    ),
                ),
                (
                    "body_en",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.core.blocks.CharBlock(
                                    form_classname="full title"
                                ),
                            ),
                            ("paragraph", wagtail.core.blocks.RichTextBlock()),
                            (
                                "team",
                                wagtail.core.blocks.ListBlock(
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "first_name",
                                                wagtail.core.blocks.CharBlock(),
                                            ),
                                            (
                                                "last_name",
                                                wagtail.core.blocks.CharBlock(),
                                            ),
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "bio",
                                                wagtail.core.blocks.RichTextBlock(),
                                            ),
                                        ]
                                    )
                                ),
                            ),
                        ],
                        null=True,
                    ),
                ),
                (
                    "body_fr",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.core.blocks.CharBlock(
                                    form_classname="full title"
                                ),
                            ),
                            ("paragraph", wagtail.core.blocks.RichTextBlock()),
                            (
                                "team",
                                wagtail.core.blocks.ListBlock(
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "first_name",
                                                wagtail.core.blocks.CharBlock(),
                                            ),
                                            (
                                                "last_name",
                                                wagtail.core.blocks.CharBlock(),
                                            ),
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "bio",
                                                wagtail.core.blocks.RichTextBlock(),
                                            ),
                                        ]
                                    )
                                ),
                            ),
                        ],
                        null=True,
                    ),
                ),
            ],
            options={"verbose_name": "About Page",},
            bases=("wagtailcore.page",),
        ),
    ]
